# Generated by Django 4.2.4 on 2023-08-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=1000)),
                ('op_one', models.CharField(max_length=30)),
                ('op_two', models.CharField(max_length=30)),
                ('op_three', models.CharField(max_length=30)),
                ('op_four', models.CharField(max_length=30)),
                ('op_one_count', models.IntegerField(default=0)),
                ('op_two_count', models.IntegerField(default=0)),
                ('op_three_count', models.IntegerField(default=0)),
                ('op_four_count', models.IntegerField(default=0)),
            ],
        ),
    ]
