# Generated by Django 4.2.4 on 2023-08-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_created_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='created_user',
        ),
    ]
