# Generated by Django 4.2.4 on 2023-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_poll_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Poll Owner'),
        ),
    ]
